type = "directrequest"
schemaVersion = 1
name = ""
maxTaskDuration = "0s"
externalJobID = "2868d2f9-2fdc-4c9a-bd64-37eb016ab772"
contractAddress = "0x394fdd656749CCCcc21280BBDF6CC209745f4d0D"
minContractPaymentLinkJuels = "0"
observationSource = """
fetch [type="bridge" name="orders-api1" requestData="$(jobRun)"]
tx0 [type="jsonparse" data="$(fetch)" path="tx0"]
tx1 [type="jsonparse" data="$(fetch)" path="tx1"]
submit_tx0  [type="ethtx" to="0x394fdd656749CCCcc21280BBDF6CC209745f4d0D" data="$(tx0)"]
submit_tx1  [type="ethtx" to="0x394fdd656749CCCcc21280BBDF6CC209745f4d0D" data="$(tx1)"]

fetch -> tx0 -> tx1 -> submit_tx0 -> submit_tx1
"""
